### ISSUE TITLE
Failed to activate the atomic-chrome package

### ISSUE THREAD

**Issue by HeeOne** [tuvistavie/atomic-chrome-atom#10]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [atomic-chrome](https://github.com/tuvistavie/atomic-chrome-atom) package, v0.3.0
### Stack Trace

Failed to activate the atomic-chrome package

```
At Cannot find module 'ws'

Error: Cannot find module 'ws'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\ASUS\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\ASUS\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/ASUS/.atom/packages/atomic-chrome-atom/lib/atomic-chrome.coffee:2:25)
    at Object.<anonymous> (file:///C:/Users/ASUS/.atom/packages/atomic-chrome-atom/lib/atomic-chrome.coffee:1:1)
    at Module._compile (C:\Users\ASUS\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\ASUS\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\ASUS\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\ASUS\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:715:27)
    at Package.module.exports.Package.activateNow (C:\Users\ASUS\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:173:16)
    at C:\Users\ASUS\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\ASUS\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\ASUS\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\ASUS\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\ASUS\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\ASUS\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\ASUS\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\ASUS\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\ASUS\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\ASUS\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:754:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "projectHome": "D:\\web\\github",
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.7.0
atom-ternjs, v0.14.2
atomic-chrome, v0.3.0
file-icons, v1.7.17
jslint, v1.5.1
regex-railroad-diagram, v0.16.0

# Dev
No dev packages
```

**Comment by danhper** [comment]
Sorry to be so late, I completely missed this.
I suspect that the ws module did not build correctly on Windows.
Is python on your path? I think it is required for node-gyp to work.
