### ISSUE TITLE
Uncaught TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by mejiaj** [tuvistavie/atomic-chrome-atom#24]
[Enter steps to reproduce:]

1. Focus on text box in Chrome (Codepen.io in this case).
2. Click on Atomic Chrome browser extension

**Atom**: 1.19.0-beta2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [atomic-chrome](https://github.com/tuvistavie/atomic-chrome-atom) package 0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'join' of undefined

```
At /Users/jmejia/.atom/packages/atomic-chrome/lib/ws-handler.coffee:36

TypeError: Cannot read property 'join' of undefined
    at WSHandler.module.exports.WSHandler.sendChanges (/packages/atomic-chrome/lib/ws-handler.coffee:36:40)
    at /packages/atomic-chrome/lib/ws-handler.coffee:29:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:625:38
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDidChangeSyncEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:822:24)
    at /Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:761:35
    at Map.forEach (native)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:760:40)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:743:18)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:956:22)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:910:20)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1672:32)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1233:30
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:2620:24)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:2582:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1231:25)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1197:25)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:1576:28)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
alignment 1.1.5 
atom-beautify 0.30.3 
atom-idiomatic-comments-css-snippets 0.1.0 
atom-liquid-snippets 0.3.0 
atomic-chrome 0.3.0 
docblockr 0.10.5 
editorconfig 2.2.2 
emmet 2.4.3 
expand-region 0.3.0 
expand-selection-to-quotes 0.11.0 
ghost-text 0.0.1 
highlight-selected 0.13.1 
javascript-snippets 1.2.1 
language-liquid 0.6.0 
material-palenight-syntax 1.5.2 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
php-twig 4.0.0 
pigments 0.39.1 
pristine-ui 1.0.15 
project-manager 3.3.5 
sort-lines 0.14.0 
sync-settings 0.8.2 
synced-sidebar 0.4.3 
```

**Comment by danhper** [comment]
Thank you for reporting, I will take a look.

**Comment by t9md** [comment]
This is how I fixed locally.

https://github.com/t9md/atomic-chrome-atom/commit/4adc56659b82d214745d925c9dac5254d1abf3c2

**Comment by danhper** [comment]
I used @t9md fix and published a new version, thank you.
